[debug] [2023-12-05T00:59:35.909Z] ----------------------------------------------------------------------
[debug] [2023-12-05T00:59:35.911Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\jakelyny_sousa\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js login
[debug] [2023-12-05T00:59:35.911Z] CLI Version:   12.9.1
[debug] [2023-12-05T00:59:35.912Z] Platform:      win32
[debug] [2023-12-05T00:59:35.912Z] Node Version:  v18.17.1
[debug] [2023-12-05T00:59:35.913Z] Time:          Mon Dec 04 2023 21:59:35 GMT-0300 (Horário Padrão de Brasília)
[debug] [2023-12-05T00:59:35.913Z] ----------------------------------------------------------------------
[debug] 
[info] Already logged in as jakelynysousa.a@gmail.com
[debug] [2023-12-05T00:59:41.018Z] Error: Timed out.
    at Timeout._onTimeout (C:\Users\jakelyny_sousa\AppData\Roaming\npm\node_modules\firebase-tools\lib\utils.js:254:49)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2023-12-05T01:00:55.834Z] ----------------------------------------------------------------------
[debug] [2023-12-05T01:00:55.836Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\jakelyny_sousa\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js deploy
[debug] [2023-12-05T01:00:55.836Z] CLI Version:   12.9.1
[debug] [2023-12-05T01:00:55.836Z] Platform:      win32
[debug] [2023-12-05T01:00:55.836Z] Node Version:  v18.17.1
[debug] [2023-12-05T01:00:55.837Z] Time:          Mon Dec 04 2023 22:00:55 GMT-0300 (Horário Padrão de Brasília)
[debug] [2023-12-05T01:00:55.837Z] ----------------------------------------------------------------------
[debug] 
[debug] [2023-12-05T01:00:55.905Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2023-12-05T01:00:55.906Z] > authorizing via signed-in user (jakelynysousa.a@gmail.com)
[debug] [2023-12-05T01:00:55.906Z] [iam] checking project templatecrudmui for permissions ["datastore.indexes.create","datastore.indexes.delete","datastore.indexes.list","datastore.indexes.update","firebase.projects.get","firebasehosting.sites.update"]
[debug] [2023-12-05T01:00:55.907Z] > refreshing access token with scopes: []
[debug] [2023-12-05T01:00:55.908Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2023-12-05T01:00:55.908Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2023-12-05T01:00:55.941Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------840612139328731264836226","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: getaddrinfo ENOTFOUND www.googleapis.com
[debug] [2023-12-05T01:00:55.942Z] [iam] error while checking permissions, command may fail: FirebaseError: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2023-12-05T01:00:55.943Z] > refreshing access token with scopes: []
[debug] [2023-12-05T01:00:55.944Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[debug] [2023-12-05T01:00:55.944Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[debug] [2023-12-05T01:00:55.951Z] *** [apiv2] error from fetch(https://www.googleapis.com/oauth2/v3/token, {"headers":{},"method":"POST","body":{"_overheadLength":545,"_valueLength":212,"_valuesToMeasure":[],"writable":false,"readable":true,"dataSize":0,"maxDataSize":2097152,"pauseStreams":true,"_released":true,"_streams":[],"_currentStream":null,"_insideLoop":false,"_pendingNext":false,"_boundary":"--------------------------768805370508447666963529","_events":{},"_eventsCount":1}}): FetchError: request to https://www.googleapis.com/oauth2/v3/token failed, reason: getaddrinfo ENOTFOUND www.googleapis.com
[debug] [2023-12-05T01:00:55.951Z] Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[error] 
[error] Error: Assertion failed: resolving hosting target of a site with no site name or target name. This should have caused an error earlier
